# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "mit_stalker"
  s.version = "1.0.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Victor Costan"]
  s.date = "2013-09-06"
  s.description = "Fetches publicly available information about MIT students."
  s.email = "victor@costan.us"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.textile"
  ]
  s.files = [
    ".project",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.textile",
    "Rakefile",
    "VERSION",
    "lib/mit_stalker.rb",
    "mit_stalker.gemspec",
    "test/fixtures/mixed_response.txt",
    "test/fixtures/multi_response.txt",
    "test/fixtures/no_response.txt",
    "test/fixtures/single_response.txt",
    "test/fixtures/single_response2.txt",
    "test/helper.rb",
    "test/mit_stalker_test.rb"
  ]
  s.homepage = "http://github.com/pwnall/mit_stalker"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Fetches publicly available information about MIT students."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<mocha>, [">= 0.14.0"])
      s.add_development_dependency(%q<minitest>, [">= 4.7.3"])
      s.add_development_dependency(%q<yard>, [">= 0.8.7"])
      s.add_development_dependency(%q<bundler>, [">= 1.3.5"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.7"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<mocha>, [">= 0.14.0"])
      s.add_dependency(%q<minitest>, [">= 4.7.3"])
      s.add_dependency(%q<yard>, [">= 0.8.7"])
      s.add_dependency(%q<bundler>, [">= 1.3.5"])
      s.add_dependency(%q<jeweler>, [">= 1.8.7"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<mocha>, [">= 0.14.0"])
    s.add_dependency(%q<minitest>, [">= 4.7.3"])
    s.add_dependency(%q<yard>, [">= 0.8.7"])
    s.add_dependency(%q<bundler>, [">= 1.3.5"])
    s.add_dependency(%q<jeweler>, [">= 1.8.7"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

