# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: mit_stalker 1.0.7 ruby lib

Gem::Specification.new do |s|
  s.name = "mit_stalker"
  s.version = "1.0.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Victor Costan"]
  s.date = "2015-09-10"
  s.description = "Fetches publicly available information about MIT students."
  s.email = "victor@costan.us"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.textile"
  ]
  s.files = [
    ".project",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.textile",
    "Rakefile",
    "VERSION",
    "lib/mit_stalker.rb",
    "mit_stalker.gemspec",
    "test/fixtures/mixed_response.txt",
    "test/fixtures/multi_response.txt",
    "test/fixtures/no_response.txt",
    "test/fixtures/single_response.txt",
    "test/fixtures/single_response2.txt",
    "test/helper.rb",
    "test/mit_stalker_test.rb"
  ]
  s.homepage = "http://github.com/pwnall/mit_stalker"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5"
  s.summary = "Fetches publicly available information about MIT students."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<net-ldap>, [">= 0.11"])
      s.add_development_dependency(%q<mocha>, [">= 1.1.0"])
      s.add_development_dependency(%q<minitest>, [">= 5.8.0"])
      s.add_development_dependency(%q<yard>, [">= 0.8.7.6"])
      s.add_development_dependency(%q<bundler>, [">= 1.6.0"])
      s.add_development_dependency(%q<jeweler>, [">= 2.0.1"])
    else
      s.add_dependency(%q<net-ldap>, [">= 0.11"])
      s.add_dependency(%q<mocha>, [">= 1.1.0"])
      s.add_dependency(%q<minitest>, [">= 5.8.0"])
      s.add_dependency(%q<yard>, [">= 0.8.7.6"])
      s.add_dependency(%q<bundler>, [">= 1.6.0"])
      s.add_dependency(%q<jeweler>, [">= 2.0.1"])
    end
  else
    s.add_dependency(%q<net-ldap>, [">= 0.11"])
    s.add_dependency(%q<mocha>, [">= 1.1.0"])
    s.add_dependency(%q<minitest>, [">= 5.8.0"])
    s.add_dependency(%q<yard>, [">= 0.8.7.6"])
    s.add_dependency(%q<bundler>, [">= 1.6.0"])
    s.add_dependency(%q<jeweler>, [">= 2.0.1"])
  end
end

